/**
 * TypeRadar — Word Lists & Quotes
 * Covers: en, tr, az, es, de, fr, it, pt, ru, ja, ko, zh, ar, hi, nl, pl, sv, no, da, fi, cs, ro, hu, el, id, vi, th, uk, fa, he
 */

const WORDS = {
  en: [
    "the","be","to","of","and","a","in","that","have","it","for","not","on","with",
    "he","as","you","do","at","this","but","his","by","from","they","we","say","her",
    "she","or","an","will","my","one","all","would","there","their","what","so","up",
    "out","if","about","who","get","which","go","me","when","make","can","like","time",
    "no","just","him","know","take","people","into","year","your","good","some","could",
    "them","see","other","than","then","now","look","only","come","its","over","think",
    "also","back","after","use","two","how","our","work","first","well","way","even",
    "new","want","because","any","these","give","day","most","us","great","between",
    "need","large","often","hand","high","place","hold","turn","help","start","never",
    "talk","last","long","show","keep","life","move","live","feel","ask","child","again",
    "point","light","open","seem","next","white","begin","walk","example","paper",
    "always","music","mark","letter","until","mile","river","car","feet","care","second",
    "book","carry","took","science","eat","room","friend","began","idea","fish",
    "mountain","stop","once","hear","horse","cut","sure","watch","color","face","wood",
    "main","enough","plain","girl","usual","young","ready","above","ever","red","list",
    "thought","city","play","small","number","off","try","kind","picture","change",
    "spell","air","away","animal","house","page","mother","answer","found","study",
    "still","learn","should","world","every","near","add","food","own","below","country",
    "plant","school","father","tree","earth","eye","story","saw","left","few","while",
    "along","might","close","something","hard","together","got","group","run","important",
    "children","side","night","sea","grow","four","state","without","later","miss",
    "real","almost","let","sometimes","song","being","leave","family","body","stand",
    "sun","questions","area","dog","problem","complete","knew","since","piece","told",
    "usually","easy","heard","order","door","become","top","ship","across","today",
    "during","short","better","best","however","low","hours","black","products",
    "happened","whole","measure","remember","early","waves","reached","listen","wind",
    "rock","space","covered","fast","several","himself","toward","five","step","morning",
    "passed","true","hundred","against","pattern","table","north","slowly","money",
    "map","farm","pulled","draw","voice","power","town","fine","drive","meant","done",
    "paint","language","among","grand","ball","warm","common","bring","explain","dry",
    "though","shape","deep","thousands","clear","equation","government","filled","heat",
    "full","hot","check","object","rule","noun","cannot","able","six","size","dark",
    "material","special","heavy","pair","circle","include","built","mass","half",
    "maybe","surprise","gold","milk","quiet","natural","lot","stone","act","build",
    "middle","speed","count","someone","sail","rolled","bear","wonder","smiled","angle",
    "bottom","trip","hole","poor","fight","died","beat","exactly","remain","dress",
    "iron","agree","compare","crowd","poem","enjoy","indicate","except","expect","flat",
    "interesting","sense","string","blow","famous","value","wings","movement","finally",
    "note","ring","free","green","sleep","three","made","through","hold","come","place"
  ],
  tr: [
    "bir","ve","bu","ile","için","ben","sen","biz","onlar","var","çok","daha","gibi",
    "olarak","ki","de","ne","ama","veya","her","hiç","nasıl","neden","zaman","iyi",
    "kötü","büyük","küçük","yeni","eski","gün","yıl","insan","dünya","hayat","zor",
    "kolay","hızlı","yavaş","güzel","doğru","yanlış","ilk","son","başka","önemli",
    "bilgi","sevgi","yol","ev","şehir","para","iş","su","renk","ses","göz","el","baş",
    "yer","gece","sabah","hava","ışık","kapı","masa","kitap","söz","düşünce","gün",
    "gelmek","gitmek","görmek","bilmek","istemek","sevmek","olmak","yapmak","söylemek",
    "bulmak","almak","vermek","bakmak","çalışmak","düşünmek","konuşmak","anlamak",
    "okumak","yazmak","öğrenmek","beklemek","görüşmek","dönmek","getirmek","götürmek",
    "koşmak","oturmak","kalkmak","girmek","çıkmak","açmak","kapamak","tutmak",
    "bırakmak","başlamak","bitmek","seçmek","sormak","cevap","saat","dakika","hafta",
    "ay","yüz","bin","araba","uçak","gemi","telefon","bilgisayar","internet","müzik",
    "film","okul","hastane","market","restoran","park","sokak","cadde","bina","köprü",
    "deniz","göl","nehir","dağ","orman","çiçek","ağaç","taş","toprak","ateş","kar",
    "yağmur","güneş","gökyüzü","bulut","bugün","yarın","dün","şimdi","sonra","önce",
    "hep","artık","henüz","sadece","bile","zaten","belki","evet","hayır","tamam",
    "lütfen","teşekkür","merhaba","günaydın","sıcak","soğuk","temiz","kirli","açık",
    "kapalı","dolu","boş","ağır","hafif","sert","yumuşak","gerçek","yalan","anlam",
    "durum","sorun","çözüm","fikir","plan","sonuç","başarı","hata","kural","örnek",
    "sistem","bilim","sanat","spor","tarih","doğa","toplum","aile","çocuk","anne",
    "baba","kardeş","arkadaş","komşu","öğretmen","doktor","mühendis","yazar",
    "gazeteci","avukat","hemşire","polis","asker","çiftçi","öğrenci","patron","işçi",
    "müdür","başkan","kral","kraliçe","kahraman","düşman","misafir","yolcu",
    "sabah","akşam","öğle","güneş","ay","yıldız","gökyüzü","toprak","deniz","dağ",
    "orman","çiçek","kuş","balık","at","kedi","köpek","arı","ağaç","yaprak","kök",
    "meyve","elma","ekmek","süt","yumurta","et","sebze","çorba","pilav","çay","kahve"
  ],
  az: [
    "və","bu","ilə","üçün","mən","sən","biz","onlar","var","çox","daha","kimi","olar",
    "ki","de","nə","amma","ya","hər","heç","necə","niyə","zaman","yaxşı","pis","böyük",
    "kiçik","yeni","köhnə","gün","il","insan","dünya","həyat","çətin","asan","sürətli",
    "yavaş","gözəl","doğru","yanlış","ilk","son","başqa","vacib","bilgi","sevgi","yol",
    "ev","şəhər","pul","iş","su","rəng","səs","göz","əl","baş","yer","gecə","səhər",
    "hava","işıq","qapı","masa","kitab","söz","düşüncə","gəlmək","getmək","görmək",
    "bilmək","istəmək","sevmək","olmaq","etmək","demək","tapmaq","almaq","vermək",
    "baxmaq","çalışmaq","düşünmək","danışmaq","anlamaq","oxumaq","yazmaq","öyrənmək",
    "gözləmək","görüşmək","dönmək","gətirmək","aparmaq","qaçmaq","oturmaq","qalxmaq",
    "girmək","çıxmaq","açmaq","bağlamaq","tutmaq","buraxmaq","başlamaq","bitmək",
    "seçmək","soruşmaq","cavab","saat","dəqiqə","həftə","ay","yüz","min","maşın",
    "təyyarə","gəmi","telefon","kompüter","internet","musiqi","film","məktəb",
    "xəstəxana","bazar","restoran","park","küçə","prospekt","bina","körpü","dəniz",
    "göl","çay","dağ","meşə","çiçək","ağac","daş","torpaq","od","qar","yağış",
    "günəş","səma","bulud","sabah","günorta","axşam","gecə","bu gün","sabah","dünən",
    "indi","sonra","əvvəl","həmişə","artıq","hələ","təkcə","hətta","bəlkə","bəli",
    "yox","tamam","salam","günaydın","isti","soyuq","təmiz","açıq","bağlı","dolu",
    "boş","ağır","yüngül","sərt","yumşaq","gerçək","yalan","vacib","məna","vəziyyət",
    "problem","həll","fikir","plan","nəticə","uğur","səhv","qayda","nümunə","sistem",
    "elm","sənət","idman","tarix","təbiət","cəmiyyət","ailə","uşaq","ana","ata",
    "qardaş","bacı","dost","qonşu","müəllim","həkim","mühəndis","yazıçı","jurnalist",
    "vəkil","polis","əsgər","tələbə","işçi","direktor","prezident","qəhrəman","qonaq",
    "nəfəs","sevincli","kədərli","güclü","zəif","yeni","köhnə","gənc","qoca","xoşbəxt"
  ],
  es: [
    "el","la","de","que","y","a","en","un","ser","se","no","haber","por","con","su",
    "para","como","estar","tener","le","lo","todo","pero","más","hacer","o","poder",
    "decir","este","ir","otro","ese","si","me","ya","ver","porque","dar","cuando",
    "muy","sin","vez","mucho","saber","sobre","mi","alguno","mismo","yo","también",
    "hasta","año","dos","querer","entre","así","primero","desde","grande","eso","ni",
    "nos","llegar","pasar","tiempo","ella","día","uno","bien","poco","deber","entonces",
    "poner","cosa","tanto","hombre","parecer","nuestro","tan","donde","ahora","parte",
    "después","vida","quedar","siempre","creer","hablar","llevar","dejar","nada","cada",
    "seguir","menos","verdad","aquí","forma","contra","partir","orden","muerte","noche",
    "nunca","agua","aire","lugar","ayuda","voz","mundo","tierra","madre","padre","hijo",
    "hermano","casa","calle","puerta","mesa","silla","libro","fuego","mar","cielo","sol",
    "luna","estrella","flor","árbol","animal","perro","gato","pájaro","pez","rojo","azul",
    "verde","amarillo","negro","blanco","grande","pequeño","alto","bajo","bueno","malo",
    "bonito","feo","caliente","frío","rápido","lento","duro","blando","feliz","triste",
    "cansado","enfermo","contento","amor","odio","paz","guerra","sueño","realidad",
    "cierto","falso","libre","fácil","difícil","joven","mayor","mejor","peor","lejos",
    "cerca","dentro","fuera","arriba","abajo","delante","detrás","antes","después",
    "ayer","hoy","mañana","siempre","nunca","pronto","tarde","temprano","ahora",
    "entonces","mientras","durante","hasta","desde","entre","según","contra","hacia",
    "para","por","sin","sobre","tras","mediante","excepto","incluso","además","tampoco",
    "ciudad","país","gente","trabajo","dinero","comida","pan","leche","carne","fruta",
    "escuela","hospital","mercado","restaurant","camino","puente","lago","río","montaña"
  ],
  de: [
    "der","die","das","ist","ein","und","ich","nicht","mit","von","auf","dem","des",
    "den","als","auch","es","an","bei","wird","aber","nach","durch","wenn","uns","oder",
    "so","zum","Sie","hat","nur","noch","kann","im","sich","wie","sein","war","haben",
    "werden","über","aus","wir","mehr","er","sind","sehr","was","hat","ihr","man",
    "haben","wird","dass","einer","um","vor","diese","muss","alle","schon","hier","doch",
    "mal","zwei","erste","nach","Zeit","gibt","viel","für","immer","große","bis","ihm",
    "dabei","weil","damit","dieser","wieder","gegen","dann","machen","hat","Arbeit",
    "Jahren","Welt","Jahr","Menschen","Deutschland","Stadt","Leben","Kinder","Hand",
    "Haus","Mann","Frau","Kind","Tag","Nacht","Morgen","Abend","Wasser","Feuer","Erde",
    "Luft","Baum","Blume","Tier","Hund","Katze","Vogel","Fisch","Brot","Milch","Fleisch",
    "Schule","Krankenhaus","Markt","Restaurant","Brücke","Berg","See","Fluss","Wald",
    "rot","blau","grün","gelb","schwarz","weiß","groß","klein","alt","neu","gut","schlecht",
    "schnell","langsam","warm","kalt","hart","weich","glücklich","traurig","müde","gesund",
    "schön","hässlich","stark","schwach","jung","alt","weit","nah","oben","unten","heute",
    "morgen","gestern","jetzt","später","früher","immer","niemals","hier","dort","links",
    "rechts","vorne","hinten","innen","außen","zwischen","neben","hinter","vor","über",
    "unter","durch","gegen","ohne","mit","für","bei","von","zu","an","in","auf","nach",
    "aus","seit","bis","trotz","während","wegen","statt","außer","dank","entlang","gemäß"
  ],
  fr: [
    "le","la","les","de","un","une","des","et","est","en","au","du","il","elle","nous",
    "vous","ils","elles","ce","on","que","qui","ne","pas","je","tu","se","à","par","sur",
    "avec","pour","dans","plus","ou","mais","donc","or","ni","car","très","bien","aussi",
    "tout","même","comme","quand","puis","encore","déjà","toujours","jamais","souvent",
    "ici","là","où","quoi","comment","pourquoi","combien","quel","quelle","son","sa","ses",
    "mon","ma","mes","ton","ta","tes","notre","votre","leur","leurs","y","en","lui","eux",
    "être","avoir","faire","aller","venir","voir","savoir","pouvoir","vouloir","devoir",
    "prendre","donner","parler","penser","croire","trouver","partir","arriver","rester",
    "monde","vie","homme","femme","enfant","jour","nuit","matin","soir","temps","an","ans",
    "maison","rue","ville","pays","eau","feu","terre","air","arbre","fleur","animal","chien",
    "chat","oiseau","poisson","pain","lait","viande","école","hôpital","marché","restaurant",
    "pont","montagne","lac","rivière","forêt","rouge","bleu","vert","jaune","noir","blanc",
    "grand","petit","vieux","nouveau","bon","mauvais","beau","laid","rapide","lent","chaud",
    "froid","dur","doux","heureux","triste","fatigué","malade","fort","faible","jeune",
    "loin","près","haut","bas","avant","après","pendant","depuis","jusqu","entre","parmi",
    "contre","vers","chez","sous","dessus","dedans","dehors","gauche","droite","devant",
    "derrière","hier","aujourd","demain","maintenant","bientôt","longtemps","souvent"
  ],
  it: [
    "il","la","lo","i","gli","le","di","un","una","e","è","in","che","con","per","da",
    "a","su","non","si","ha","ho","hai","abbiamo","avete","hanno","sono","sei","siamo",
    "siete","ma","o","se","anche","così","già","ancora","sempre","mai","molto","poco",
    "qui","là","dove","come","quando","perché","quanto","quale","questo","quello","tutto",
    "fare","essere","avere","andare","venire","vedere","sapere","potere","volere","dovere",
    "prendere","dare","parlare","pensare","credere","trovare","partire","arrivare","stare",
    "mondo","vita","uomo","donna","bambino","giorno","notte","mattina","sera","tempo",
    "anno","casa","strada","città","paese","acqua","fuoco","terra","aria","albero","fiore",
    "animale","cane","gatto","uccello","pesce","pane","latte","carne","scuola","ospedale",
    "mercato","ristorante","ponte","montagna","lago","fiume","foresta","rosso","blu","verde",
    "giallo","nero","bianco","grande","piccolo","vecchio","nuovo","buono","cattivo","bello",
    "brutto","veloce","lento","caldo","freddo","duro","morbido","felice","triste","stanco",
    "malato","forte","debole","giovane","anziano","lontano","vicino","sopra","sotto","prima",
    "dopo","durante","da","fino","tra","tra","contro","verso","senza","con","per","da",
    "oggi","ieri","domani","adesso","presto","tardi","subito","spesso","sempre","mai"
  ],
  pt: [
    "o","a","os","as","de","um","uma","e","em","que","com","por","para","não","se",
    "na","no","ao","do","da","mais","como","mas","ou","quando","muito","já","ainda",
    "bem","só","sobre","entre","depois","antes","também","sem","até","cada","todo",
    "todos","todas","isto","isso","aquilo","eu","tu","ele","ela","nós","vós","eles",
    "elas","ser","ter","fazer","ir","vir","ver","saber","poder","querer","dever",
    "tomar","dar","falar","pensar","crer","encontrar","partir","chegar","ficar","estar",
    "mundo","vida","homem","mulher","criança","dia","noite","manhã","tarde","tempo",
    "ano","casa","rua","cidade","país","água","fogo","terra","ar","árvore","flor",
    "animal","cão","gato","pássaro","peixe","pão","leite","carne","escola","hospital",
    "mercado","restaurante","ponte","montanha","lago","rio","floresta","vermelho","azul",
    "verde","amarelo","preto","branco","grande","pequeno","velho","novo","bom","mau",
    "bonito","feio","rápido","lento","quente","frio","duro","mole","feliz","triste",
    "cansado","doente","forte","fraco","jovem","idoso","longe","perto","cima","baixo",
    "antes","depois","durante","desde","até","entre","contra","sem","com","para","por",
    "hoje","ontem","amanhã","agora","logo","tarde","cedo","sempre","nunca","às vezes"
  ],
  ru: [
    "и","в","не","на","я","что","тот","он","она","они","мы","вы","это","с","а","как",
    "но","к","из","у","по","за","то","так","же","все","от","да","о","его","она","есть",
    "уже","если","или","ни","бы","там","ещё","при","этот","другой","через","мне","нас",
    "вас","им","нет","раз","для","можно","много","который","быть","иметь","делать",
    "идти","видеть","знать","мочь","хотеть","думать","говорить","найти","прийти",
    "стать","взять","дать","сказать","работа","жизнь","мир","человек","день","ночь",
    "утро","вечер","время","год","дом","город","страна","вода","огонь","земля","воздух",
    "дерево","цветок","животное","собака","кошка","птица","рыба","хлеб","молоко","мясо",
    "школа","больница","рынок","ресторан","мост","гора","озеро","река","лес","красный",
    "синий","зелёный","жёлтый","чёрный","белый","большой","маленький","старый","новый",
    "хороший","плохой","красивый","некрасивый","быстрый","медленный","тёплый","холодный",
    "твёрдый","мягкий","счастливый","грустный","усталый","больной","сильный","слабый",
    "молодой","пожилой","далеко","близко","выше","ниже","сегодня","вчера","завтра",
    "теперь","скоро","поздно","рано","всегда","никогда","часто","иногда","здесь","там"
  ],
  ja: [
    "の","に","は","を","が","と","で","て","も","な","い","た","か","こと","から",
    "する","ある","いる","なる","言う","見る","行く","来る","思う","知る","入る","出る",
    "時","人","年","大","日本","中","長い","本","見","分","東","京","国","高い","大きい",
    "小さい","新しい","古い","良い","悪い","早い","遅い","熱い","冷たい","難しい","簡単",
    "今日","明日","昨日","今","後","前","上","下","右","左","中","外","近い","遠い",
    "家","学校","病院","店","橋","山","川","海","森","花","木","犬","猫","鳥","魚",
    "水","火","風","空","雨","雪","光","音","色","赤","青","緑","黄","黒","白",
    "食べる","飲む","読む","書く","話す","聞く","買う","売る","作る","使う","開ける","閉める",
    "お父さん","お母さん","子供","友達","先生","医者","仕事","お金","時間","場所","問題","答え"
  ],
  ko: [
    "이","가","을","를","은","는","에","에서","으로","와","과","도","만","도","의",
    "하다","있다","없다","되다","보다","가다","오다","알다","만들다","살다","쓰다",
    "아","나","우리","여러분","그","그녀","사람","시간","일","년","나라","세계",
    "집","학교","병원","시장","식당","다리","산","강","바다","숲","꽃","나무","개","고양이",
    "새","물고기","물","불","바람","하늘","비","눈","빛","소리","색","빨간","파란","초록",
    "노란","검은","흰","크다","작다","낡다","새롭다","좋다","나쁘다","예쁘다","빠르다",
    "느리다","따뜻하다","차갑다","어렵다","쉽다","오늘","어제","내일","지금","나중","일찍",
    "항상","절대","자주","때때로","여기","저기","위","아래","오른쪽","왼쪽","안","밖",
    "먹다","마시다","읽다","쓰다","말하다","듣다","사다","팔다","만들다","사용하다",
    "아버지","어머니","아이","친구","선생님","의사","돈","장소","문제","답"
  ],
  zh: [
    "的","了","在","是","我","有","和","就","不","人","都","一","一个","上","也","很",
    "到","说","要","去","你","会","着","没有","看","好","自己","这","那","来","用",
    "们","以","中","时","地","年","得","如果","但是","因为","所以","虽然","然后","而且",
    "这个","那个","什么","为什么","怎么","哪里","谁","多少","多久","多大","什么时候",
    "做","想","知道","需要","喜欢","爱","恨","感谢","帮助","学习","工作","生活",
    "家","学校","医院","商店","餐厅","桥","山","河","海","森林","花","树","狗","猫",
    "鸟","鱼","水","火","风","天空","雨","雪","光","声音","颜色","红","蓝","绿","黄",
    "黑","白","大","小","旧","新","好","坏","漂亮","快","慢","热","冷","难","容易",
    "今天","昨天","明天","现在","以后","以前","总是","从不","常常","有时","这里","那里",
    "上面","下面","左边","右边","里面","外面","父亲","母亲","孩子","朋友","老师","医生"
  ],
  ar: [
    "و","في","من","على","أن","إلى","هو","هي","نحن","أنت","أنتم","هم","مع","عن","هذا",
    "هذه","ذلك","التي","الذي","لكن","أو","ثم","إذا","لأن","حتى","قد","كان","كل","بعض",
    "كثير","قليل","جيد","سيء","كبير","صغير","جديد","قديم","سريع","بطيء","ساخن","بارد",
    "صعب","سهل","اليوم","أمس","غداً","الآن","دائماً","أبداً","هنا","هناك","فوق","تحت",
    "يمين","يسار","قبل","بعد","بيت","مدرسة","مستشفى","سوق","مطعم","جسر","جبل","نهر",
    "بحر","غابة","زهرة","شجرة","كلب","قطة","طائر","سمكة","ماء","نار","هواء","سماء",
    "مطر","ثلج","ضوء","صوت","لون","أحمر","أزرق","أخضر","أصفر","أسود","أبيض","كبير",
    "صغير","قديم","جديد","حسن","سيء","جميل","قبيح","سريع","بطيء","أب","أم","ولد","بنت",
    "صديق","معلم","طبيب","عمل","مال","مكان","مشكلة","جواب","سؤال","كتاب","قلم","طعام",
    "خبز","حليب","لحم","شاي","قهوة","عائلة","حياة","عالم","ناس","وقت","يوم","ليلة"
  ],
  hi: [
    "और","का","की","के","है","में","को","से","पर","एक","यह","वह","हम","आप","वे",
    "हो","था","थे","थी","होना","करना","जाना","आना","देखना","जानना","लेना","देना",
    "बात","समय","आदमी","औरत","बच्चा","दिन","रात","साल","घर","शहर","देश","दुनिया",
    "पानी","आग","हवा","आकाश","बारिश","बर्फ","रोशनी","आवाज़","रंग","लाल","नीला",
    "हरा","पीला","काला","सफ़ेद","बड़ा","छोटा","पुराना","नया","अच्छा","बुरा","खूबसूरत",
    "तेज़","धीमा","गर्म","ठंडा","मुश्किल","आसान","आज","कल","अभी","हमेशा","कभी नहीं",
    "यहाँ","वहाँ","ऊपर","नीचे","दाईं","बाईं","पहले","बाद में","स्कूल","अस्पताल",
    "बाज़ार","रेस्टोरेंट","पहाड़","नदी","समुद्र","जंगल","फूल","पेड़","कुत्ता","बिल्ली",
    "पक्षी","मछली","रोटी","दूध","मांस","चाय","परिवार","दोस्त","शिक्षक","डॉक्टर",
    "पैसे","जगह","सवाल","जवाब","किताब","खाना","काम","जीवन","लोग","प्यार","खुशी","दुःख"
  ],
  nl: [
    "de","het","een","en","in","van","op","te","zijn","dat","voor","met","als","niet",
    "is","aan","heeft","maar","ook","er","door","bij","om","uit","over","dan","of","zo",
    "tot","worden","hij","zij","we","jullie","ze","dit","die","wat","wie","hoe","waar",
    "wanneer","waarom","groot","klein","oud","nieuw","goed","slecht","mooi","lelijk",
    "snel","langzaam","warm","koud","moeilijk","gemakkelijk","vandaag","gisteren",
    "morgen","nu","later","vroeg","altijd","nooit","hier","daar","boven","beneden",
    "links","rechts","voor","achter","thuis","school","ziekenhuis","winkel","restaurant",
    "brug","berg","rivier","zee","bos","bloem","boom","hond","kat","vogel","vis",
    "water","vuur","lucht","hemel","regen","sneeuw","licht","geluid","kleur","rood",
    "blauw","groen","geel","zwart","wit","vader","moeder","kind","vriend","leraar",
    "dokter","werk","geld","plaats","vraag","antwoord","eten","brood","melk","vlees",
    "leven","wereld","mensen","tijd","dag","nacht","jaar","land","familie","liefde"
  ],
  pl: [
    "i","w","na","z","do","nie","że","się","to","jest","jak","ale","go","po","jego",
    "jej","ich","już","też","tak","czy","co","który","tylko","tej","ten","tego","ta",
    "być","mieć","robić","iść","przyjść","widzieć","wiedzieć","móc","chcieć","myśleć",
    "mówić","znaleźć","wziąć","dać","człowiek","czas","rok","dzień","noc","rano",
    "wieczór","dom","miasto","kraj","świat","woda","ogień","ziemia","powietrze","drzewo",
    "kwiat","zwierzę","pies","kot","ptak","ryba","chleb","mleko","mięso","szkoła",
    "szpital","rynek","restauracja","most","góra","rzeka","morze","las","czerwony",
    "niebieski","zielony","żółty","czarny","biały","duży","mały","stary","nowy","dobry",
    "zły","piękny","szybki","wolny","ciepły","zimny","trudny","łatwy","dziś","wczoraj",
    "jutro","teraz","zawsze","nigdy","tutaj","tam","góra","dół","ojciec","matka","dziecko",
    "przyjaciel","nauczyciel","doktor","pieniądze","miejsce","pytanie","odpowiedź","życie"
  ],
  sv: [
    "och","i","att","det","är","en","av","på","med","för","som","inte","till","han",
    "hon","vi","de","ett","om","men","från","var","sig","hur","när","vad","vem","där",
    "kan","vill","ska","ha","har","hade","var","bli","stor","liten","gammal","ny","bra",
    "dålig","vacker","snabb","långsam","varm","kall","svår","lätt","idag","igår",
    "imorgon","nu","alltid","aldrig","här","där","upp","ner","vänster","höger","hemma",
    "skola","sjukhus","affär","restaurang","bro","berg","flod","hav","skog","blomma",
    "träd","hund","katt","fågel","fisk","vatten","eld","luft","himmel","regn","snö",
    "ljus","ljud","färg","röd","blå","grön","gul","svart","vit","far","mor","barn",
    "vän","lärare","läkare","pengar","plats","fråga","svar","bröd","mjölk","kött",
    "liv","värld","folk","tid","dag","natt","år","land","familj","kärlek","glädje","sorg"
  ],
  no: [
    "og","i","at","det","er","en","av","på","med","for","som","ikke","til","han",
    "hun","vi","de","et","om","men","fra","var","seg","hvordan","når","hva","hvem",
    "der","kan","vil","skal","ha","har","hadde","stor","liten","gammel","ny","bra",
    "dårlig","vakker","rask","langsom","varm","kald","vanskelig","lett","i dag","i går",
    "i morgen","nå","alltid","aldri","her","der","opp","ned","venstre","høyre","hjem",
    "skole","sykehus","butikk","restaurant","bro","fjell","elv","hav","skog","blomst",
    "tre","hund","katt","fugl","fisk","vann","ild","luft","himmel","regn","snø",
    "lys","lyd","farge","rød","blå","grønn","gul","svart","hvit","far","mor","barn",
    "venn","lærer","lege","penger","sted","spørsmål","svar","brød","melk","kjøtt",
    "liv","verden","folk","tid","dag","natt","år","land","familie","kjærlighet","glede"
  ],
  da: [
    "og","i","at","det","er","en","af","på","med","for","som","ikke","til","han",
    "hun","vi","de","et","om","men","fra","var","sig","hvordan","når","hvad","hvem",
    "der","kan","vil","skal","ha","har","havde","stor","lille","gammel","ny","god",
    "dårlig","smuk","hurtig","langsom","varm","kold","svær","let","i dag","i går",
    "i morgen","nu","altid","aldrig","her","der","op","ned","venstre","højre","hjem",
    "skole","hospital","butik","restaurant","bro","bjerg","flod","hav","skov","blomst",
    "træ","hund","kat","fugl","fisk","vand","ild","luft","himmel","regn","sne",
    "lys","lyd","farve","rød","blå","grøn","gul","sort","hvid","far","mor","barn",
    "ven","lærer","læge","penge","sted","spørgsmål","svar","brød","mælk","kød",
    "liv","verden","folk","tid","dag","nat","år","land","familie","kærlighed","glæde"
  ],
  fi: [
    "ja","on","ei","se","oli","hän","me","te","he","että","jos","kuin","kun","niin",
    "jo","tai","vaan","mutta","myös","vielä","aina","ei","tässä","siellä","mihin",
    "olla","tehdä","mennä","tulla","nähdä","tietää","voida","haluta","ajatella","puhua",
    "löytää","ottaa","antaa","ihminen","aika","vuosi","päivä","yö","aamu","ilta",
    "talo","kaupunki","maa","maailma","vesi","tuli","maa","ilma","puu","kukka","eläin",
    "koira","kissa","lintu","kala","leipä","maito","liha","koulu","sairaala","kauppa",
    "ravintola","silta","vuori","joki","meri","metsä","punainen","sininen","vihreä",
    "keltainen","musta","valkoinen","iso","pieni","vanha","uusi","hyvä","huono","kaunis",
    "nopea","hidas","lämmin","kylmä","vaikea","helppo","tänään","eilen","huomenna",
    "nyt","aina","ei koskaan","täällä","siellä","ylös","alas","isä","äiti","lapsi",
    "ystävä","opettaja","lääkäri","raha","paikka","kysymys","vastaus","elämä","perhe"
  ],
  cs: [
    "a","v","na","z","do","ne","že","se","to","je","jak","ale","go","po","jeho",
    "jejich","jen","tak","nebo","co","který","jako","tento","být","mít","dělat","jít",
    "přijít","vidět","vědět","moci","chtít","myslet","říct","najít","vzít","dát",
    "člověk","čas","rok","den","noc","ráno","večer","dům","město","země","svět","voda",
    "oheň","vzduch","strom","květ","zvíře","pes","kočka","pták","ryba","chléb","mléko",
    "maso","škola","nemocnice","trh","restaurace","most","hora","řeka","moře","les",
    "červený","modrý","zelený","žlutý","černý","bílý","velký","malý","starý","nový",
    "dobrý","špatný","krásný","rychlý","pomalý","teplý","studený","těžký","snadný",
    "dnes","včera","zítra","teď","vždy","nikdy","tady","tam","otec","matka","dítě",
    "přítel","učitel","doktor","peníze","místo","otázka","odpověď","život","rodina"
  ],
  ro: [
    "și","în","la","de","că","nu","este","pe","cu","o","un","din","pentru","ce","el",
    "ea","noi","voi","ei","ele","acest","acel","care","cum","când","unde","cine","cât",
    "fi","avea","face","merge","veni","vedea","ști","putea","vrea","gândi","vorbi",
    "găsi","lua","da","om","timp","an","zi","noapte","dimineață","seară","casă","oraș",
    "țară","lume","apă","foc","pământ","aer","copac","floare","animal","câine","pisică",
    "pasăre","pește","pâine","lapte","carne","școală","spital","piață","restaurant","pod",
    "munte","râu","mare","pădure","roșu","albastru","verde","galben","negru","alb","mare",
    "mic","vechi","nou","bun","rău","frumos","rapid","lent","cald","rece","greu","ușor",
    "azi","ieri","mâine","acum","mereu","niciodată","aici","acolo","sus","jos","tată",
    "mamă","copil","prieten","profesor","doctor","bani","loc","întrebare","răspuns","viață"
  ],
  hu: [
    "és","a","az","van","nem","hogy","be","ez","de","meg","is","el","ki","le","fel",
    "én","te","ő","mi","ti","ők","ez","az","aki","ami","ahogy","amikor","ahol","miért",
    "lenni","csinálni","menni","jönni","látni","tudni","tudni","akarni","gondolni",
    "mondani","találni","venni","adni","ember","idő","év","nap","éjszaka","reggel",
    "este","ház","város","ország","világ","víz","tűz","föld","levegő","fa","virág",
    "állat","kutya","macska","madár","hal","kenyér","tej","hús","iskola","kórház",
    "piac","étterem","híd","hegy","folyó","tenger","erdő","piros","kék","zöld","sárga",
    "fekete","fehér","nagy","kicsi","öreg","új","jó","rossz","gyönyörű","gyors","lassú",
    "meleg","hideg","nehéz","könnyű","ma","tegnap","holnap","most","mindig","soha",
    "itt","ott","fenn","lenn","apa","anya","gyermek","barát","tanár","orvos","pénz",
    "hely","kérdés","válasz","élet","szeretet","öröm","szomorúság","erős","gyenge"
  ],
  el: [
    "και","σε","να","από","που","για","με","ή","αν","ότι","τον","την","το","τα","τους",
    "των","οι","της","του","εγώ","εσύ","αυτός","αυτή","αυτό","εμείς","εσείς","αυτοί",
    "είναι","έχω","κάνω","πηγαίνω","έρχομαι","βλέπω","ξέρω","μπορώ","θέλω","σκέφτομαι",
    "μιλάω","βρίσκω","παίρνω","δίνω","άνθρωπος","χρόνος","χρόνια","ημέρα","νύχτα",
    "πρωί","βράδυ","σπίτι","πόλη","χώρα","κόσμος","νερό","φωτιά","γη","αέρας","δέντρο",
    "λουλούδι","ζώο","σκύλος","γάτα","πουλί","ψάρι","ψωμί","γάλα","κρέας","σχολείο",
    "νοσοκομείο","αγορά","εστιατόριο","γέφυρα","βουνό","ποτάμι","θάλασσα","δάσος",
    "κόκκινο","μπλε","πράσινο","κίτρινο","μαύρο","άσπρο","μεγάλος","μικρός","παλιός",
    "νέος","καλός","κακός","όμορφος","γρήγορος","αργός","ζεστός","κρύος","δύσκολος",
    "εύκολος","σήμερα","χθες","αύριο","τώρα","πάντα","ποτέ","εδώ","εκεί","πατέρας",
    "μητέρα","παιδί","φίλος","δάσκαλος","γιατρός","χρήματα","μέρος","ερώτηση","απάντηση"
  ],
  id: [
    "dan","di","yang","ini","itu","ke","dari","ada","tidak","dengan","untuk","dalam",
    "adalah","saya","kamu","dia","kami","mereka","kita","akan","sudah","bisa","harus",
    "mau","juga","lagi","atau","tetapi","karena","jika","ketika","bagaimana","dimana",
    "siapa","apa","kapan","berapa","pergi","datang","melihat","tahu","bisa","mau","pikir",
    "bicara","cari","ambil","beri","orang","waktu","tahun","hari","malam","pagi","sore",
    "rumah","kota","negara","dunia","air","api","tanah","udara","pohon","bunga","hewan",
    "anjing","kucing","burung","ikan","roti","susu","daging","sekolah","rumah sakit",
    "pasar","restoran","jembatan","gunung","sungai","laut","hutan","merah","biru","hijau",
    "kuning","hitam","putih","besar","kecil","tua","baru","baik","buruk","cantik","cepat",
    "lambat","panas","dingin","sulit","mudah","hari ini","kemarin","besok","sekarang",
    "selalu","tidak pernah","di sini","di sana","atas","bawah","ayah","ibu","anak",
    "teman","guru","dokter","uang","tempat","pertanyaan","jawaban","hidup","keluarga"
  ],
  vi: [
    "và","trong","của","là","có","không","với","cho","này","đó","một","được","tôi",
    "bạn","anh","chị","chúng tôi","họ","cũng","đã","sẽ","muốn","cần","phải","thì",
    "nhưng","nếu","khi","như thế nào","ở đâu","ai","gì","khi nào","bao nhiêu",
    "đi","đến","thấy","biết","có thể","muốn","nghĩ","nói","tìm","lấy","cho","người",
    "thời gian","năm","ngày","đêm","sáng","tối","nhà","thành phố","đất nước","thế giới",
    "nước","lửa","đất","không khí","cây","hoa","động vật","chó","mèo","chim","cá",
    "bánh mì","sữa","thịt","trường học","bệnh viện","chợ","nhà hàng","cầu","núi","sông",
    "biển","rừng","đỏ","xanh","xanh lá","vàng","đen","trắng","lớn","nhỏ","cũ","mới",
    "tốt","xấu","đẹp","nhanh","chậm","nóng","lạnh","khó","dễ","hôm nay","hôm qua",
    "ngày mai","bây giờ","luôn luôn","không bao giờ","đây","đó","bố","mẹ","con","bạn bè"
  ],
  th: [
    "และ","ใน","ของ","ที่","ไม่","มี","เป็น","กับ","จาก","สำหรับ","ได้","จะ","ก็","แต่",
    "หรือ","ถ้า","เมื่อ","อย่างไร","ที่ไหน","ใคร","อะไร","เมื่อไร","เท่าไร",
    "ไป","มา","เห็น","รู้","ทำ","คิด","พูด","หา","เอา","ให้","คน","เวลา","ปี","วัน",
    "คืน","เช้า","เย็น","บ้าน","เมือง","ประเทศ","โลก","น้ำ","ไฟ","ดิน","อากาศ","ต้นไม้",
    "ดอกไม้","สัตว์","หมา","แมว","นก","ปลา","ขนมปัง","นม","เนื้อ","โรงเรียน","โรงพยาบาล",
    "ตลาด","ร้านอาหาร","สะพาน","ภูเขา","แม่น้ำ","ทะเล","ป่า","แดง","น้ำเงิน","เขียว",
    "เหลือง","ดำ","ขาว","ใหญ่","เล็ก","เก่า","ใหม่","ดี","ไม่ดี","สวย","เร็ว","ช้า",
    "ร้อน","เย็น","ยาก","ง่าย","วันนี้","เมื่อวาน","พรุ่งนี้","ตอนนี้","เสมอ","ไม่เคย",
    "ที่นี่","ที่นั่น","พ่อ","แม่","ลูก","เพื่อน","ครู","หมอ","เงิน","สถานที่","คำถาม","คำตอบ"
  ],
  uk: [
    "і","в","не","на","я","що","той","він","вона","вони","ми","ви","це","з","а","як",
    "але","до","від","у","по","за","то","так","ж","всі","від","так","про","його","її",
    "є","вже","якщо","або","ні","був","там","ще","при","цей","інший","через","мені",
    "нас","вас","ним","немає","раз","для","можна","багато","який","бути","мати","робити",
    "іти","бачити","знати","могти","хотіти","думати","говорити","знайти","прийти",
    "стати","взяти","дати","сказати","робота","життя","світ","людина","день","ніч",
    "ранок","вечір","час","рік","будинок","місто","країна","вода","вогонь","земля",
    "повітря","дерево","квітка","тварина","собака","кіт","птах","риба","хліб","молоко",
    "м'ясо","школа","лікарня","ринок","ресторан","міст","гора","річка","море","ліс",
    "червоний","синій","зелений","жовтий","чорний","білий","великий","малий","старий",
    "новий","хороший","поганий","красивий","швидкий","повільний","теплий","холодний",
    "важкий","легкий","сьогодні","вчора","завтра","зараз","завжди","ніколи","тут","там"
  ],
  fa: [
    "و","در","که","به","از","این","با","است","را","یک","هم","می","نه","اما","یا",
    "اگر","چون","وقتی","چطور","کجا","کی","چه","چقدر","من","تو","او","ما","شما","آنها",
    "رفتن","آمدن","دیدن","دانستن","توانستن","خواستن","فکر کردن","صحبت کردن","پیدا کردن",
    "گرفتن","دادن","کردن","انسان","زمان","سال","روز","شب","صبح","شب","خانه","شهر",
    "کشور","دنیا","آب","آتش","زمین","هوا","درخت","گل","حیوان","سگ","گربه","پرنده",
    "ماهی","نان","شیر","گوشت","مدرسه","بیمارستان","بازار","رستوران","پل","کوه","رودخانه",
    "دریا","جنگل","قرمز","آبی","سبز","زرد","سیاه","سفید","بزرگ","کوچک","پیر","جدید",
    "خوب","بد","زیبا","سریع","آهسته","گرم","سرد","سخت","آسان","امروز","دیروز","فردا",
    "الان","همیشه","هرگز","اینجا","آنجا","بالا","پایین","پدر","مادر","بچه","دوست",
    "معلم","دکتر","پول","مکان","سوال","جواب","زندگی","خانواده","عشق","شادی","غم"
  ],
  he: [
    "ו","ב","ה","ל","מ","ש","כ","את","של","על","עם","זה","כי","לא","אם","הוא","היא",
    "הם","אנחנו","אתם","אני","אתה","גם","כבר","עוד","אבל","רק","כן","לו","לה","להם",
    "להיות","לעשות","ללכת","לבוא","לראות","לדעת","יכול","רוצה","לחשוב","לדבר",
    "למצוא","לקחת","לתת","אדם","זמן","שנה","יום","לילה","בוקר","ערב","בית","עיר",
    "ארץ","עולם","מים","אש","אדמה","אוויר","עץ","פרח","חיה","כלב","חתול","ציפור",
    "דג","לחם","חלב","בשר","בית ספר","בית חולים","שוק","מסעדה","גשר","הר","נהר",
    "ים","יער","אדום","כחול","ירוק","צהוב","שחור","לבן","גדול","קטן","ישן","חדש",
    "טוב","רע","יפה","מהיר","איטי","חם","קר","קשה","קל","היום","אתמול","מחר",
    "עכשיו","תמיד","לעולם לא","כאן","שם","אב","אם","ילד","חבר","מורה","רופא","כסף",
    "מקום","שאלה","תשובה","חיים","משפחה","אהבה","שמחה","עצב","חזק","חלש"
  ]
};

const QUOTES = [
  // ── short (≤8 words) ──────────────────────────────────────────────────────
  "Be yourself everyone else is taken.",
  "Stay hungry stay foolish.",
  "Dream big work hard.",
  "Less talk more action.",
  "Do what you love.",
  "Make it simple but significant.",
  "Simplicity is the ultimate sophistication.",
  "Code is poetry written in logic.",
  "Think different act bold.",
  "Done is better than perfect.",
  "The journey matters more than destination.",
  "Create more than you consume.",
  "Every expert was once a beginner.",
  "Small steps lead to big changes.",
  "Clarity is power.",
  // ── medium (9–15 words) ───────────────────────────────────────────────────
  "The only way to do great work is to love what you do.",
  "In the middle of every difficulty lies opportunity.",
  "Life is what happens when you are busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The only impossible journey is the one you never begin.",
  "Your time is limited so do not waste it living someone else life.",
  "In three words I can sum up everything about life it goes on.",
  "You miss one hundred percent of the shots you never take.",
  "Whether you think you can or think you cannot you are right.",
  "What you get by achieving your goals is not as important as who you become.",
  "The best time to plant a tree was twenty years ago the second best time is now.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The secret of getting ahead is getting started right now with what you have.",
  "Do not watch the clock instead do what it does and keep going forward.",
  "The harder you work for something the greater you will feel when you achieve it.",
  "A person who never made a mistake never tried anything new in their life.",
  // ── long (16–25 words) ────────────────────────────────────────────────────
  "Success is not final failure is not fatal it is the courage to continue that counts when everything feels impossible.",
  "The difference between ordinary and extraordinary is that little extra effort you put in every single day without exception.",
  "It always seems impossible until it is done and then you wonder why it took you so long to finally begin.",
  "If you want to live a happy life tie it to a goal not to people or things around you that change.",
  "Strive not to be a success but rather to be of value to those around you and to the world you live in.",
  "Twenty years from now you will be more disappointed by the things you did not do than by the ones you did so explore.",
  "The secret of getting ahead is getting started and breaking your complex overwhelming tasks into small manageable actionable steps every morning.",
  "You do not have to be great to start but you have to start to be great and that moment is always right now.",
  "The road to success and the road to failure are almost exactly the same and what separates them is your daily consistent effort.",
  // ── thicc (>25 words) ─────────────────────────────────────────────────────
  "I have not failed I have just found ten thousand ways that will not work and each one brings me closer to the solution that will finally change everything around me.",
  "The greatest glory in living lies not in never falling but in rising every time you fall because resilience is the true foundation of all great achievement in this world.",
  "It does not matter how many times you get knocked down all that matters is how many times you get up and keep pushing forward with everything you have inside you.",
  "First they ignore you then they laugh at you then they fight you then you win and when you win you realize the struggle itself was the entire point all along.",
  "The brick walls are not there to keep us out they are there to give us a chance to show how badly we want something and how far we will go to get it.",
  "If you can dream it you can do it always remember that this whole thing was started with a dream and a mouse and the belief that imagination and hard work have absolutely no limits whatsoever.",
  "Believe you can and you are halfway there the other half is showing up every single day putting in the work staying consistent even when the results are slow and the path is unclear and long."
];
