/**
 * TypeRadar — Word Lists & Quotes
 */

const WORDS = {
  en: [
    "the","be","to","of","and","a","in","that","have","it","for","not","on","with",
    "he","as","you","do","at","this","but","his","by","from","they","we","say","her",
    "she","or","an","will","my","one","all","would","there","their","what","so","up",
    "out","if","about","who","get","which","go","me","when","make","can","like","time",
    "no","just","him","know","take","people","into","year","your","good","some","could",
    "them","see","other","than","then","now","look","only","come","its","over","think",
    "also","back","after","use","two","how","our","work","first","well","way","even",
    "new","want","because","any","these","give","day","most","us","great","between",
    "need","large","often","hand","high","place","hold","turn","help","start","never",
    "talk","last","long","show","keep","life","move","live","feel","ask","child","again",
    "point","light","open","seem","next","white","begin","walk","example","paper",
    "always","music","mark","letter","until","mile","river","car","feet","care","second",
    "book","carry","took","science","eat","room","friend","began","idea","fish",
    "mountain","stop","once","hear","horse","cut","sure","watch","color","face","wood",
    "main","enough","plain","girl","usual","young","ready","above","ever","red","list",
    "thought","city","play","small","number","off","try","kind","picture","change",
    "spell","air","away","animal","house","page","mother","answer","found","study",
    "still","learn","should","world","every","near","add","food","own","below","country",
    "plant","school","father","tree","earth","eye","story","saw","left","few","while",
    "along","might","close","something","hard","together","got","group","run","important",
    "children","side","night","sea","grow","four","state","without","later","miss",
    "real","almost","let","sometimes","cut","young","song","being","leave","family",
    "body","stand","sun","questions","area","dog","birds","problem","complete","knew",
    "since","piece","told","usually","easy","heard","order","door","become","top",
    "ship","across","today","during","short","better","best","however","low","hours",
    "black","products","happened","whole","measure","remember","early","waves","reached",
    "listen","wind","rock","space","covered","fast","several","himself","toward","five",
    "step","morning","passed","vowel","true","hundred","against","pattern","numeral",
    "table","north","slowly","money","map","farm","pulled","draw","voice","power","town",
    "fine","drive","meant","done","paint","language","among","grand","ball","warm",
    "common","bring","explain","dry","though","shape","deep","thousands","clear",
    "equation","government","filled","heat","full","hot","check","object","rule","noun",
    "cannot","able","six","size","dark","material","special","heavy","pair","circle",
    "include","built","mass","half","maybe","surprise","gold","milk","quiet","natural",
    "lot","stone","act","build","middle","speed","count","consonant","someone","sail",
    "rolled","bear","wonder","smiled","angle","fraction","africa","killed","melody",
    "bottom","trip","hole","poor","fight","french","died","beat","exactly","remain",
    "dress","iron","otherwise","agree","compare","crowd","poem","enjoy","elements",
    "indicate","except","expect","flat","seven","interesting","sense","string","blow",
    "famous","value","wings","movement","finally","note","ring","free","green","sleep",
    "three","made","through","hold","come","place","white"
  ],
  tr: [
    "bir","ve","bu","ile","için","ben","sen","biz","onlar","var","çok","daha","gibi",
    "olarak","ki","de","ne","ama","veya","her","hiç","nasıl","neden","zaman","iyi",
    "kötü","büyük","küçük","yeni","eski","gün","yıl","insan","dünya","hayat","zor",
    "kolay","hızlı","yavaş","güzel","doğru","yanlış","ilk","son","başka","önemli",
    "bilgi","sevgi","yol","ev","şehir","para","iş","su","renk","ses","göz","el","baş",
    "yer","gece","sabah","hava","ışık","kapı","masa","kitap","söz","düşünce","gün",
    "gelmek","gitmek","görmek","bilmek","istemek","sevmek","olmak","yapmak","söylemek",
    "bulmak","almak","vermek","bakmak","çalışmak","düşünmek","konuşmak","anlamak",
    "okumak","yazmak","öğrenmek","beklemek","görüşmek","dönmek","getirmek","götürmek",
    "koşmak","oturmak","kalkmak","girmek","çıkmak","açmak","kapamak","tutmak",
    "bırakmak","başlamak","bitmek","seçmek","sormak","cevap","saat","dakika","hafta",
    "ay","yüz","bin","araba","uçak","gemi","telefon","bilgisayar","internet","müzik",
    "film","okul","hastane","market","restoran","park","sokak","cadde","bina","köprü",
    "deniz","göl","nehir","dağ","orman","çiçek","ağaç","taş","toprak","ateş","kar",
    "yağmur","güneş","gökyüzü","bulut","sabah","öğle","akşam","gece","bugün","yarın",
    "dün","hafta","ay","yıl","şimdi","sonra","önce","hep","artık","henüz","sadece",
    "bile","zaten","belki","evet","hayır","tamam","lütfen","teşekkür","merhaba",
    "günaydın","sıcak","soğuk","temiz","kirli","açık","kapalı","dolu","boş","ağır",
    "hafif","sert","yumuşak","gerçek","yalan","anlam","durum","sorun","çözüm","fikir",
    "plan","sonuç","başarı","hata","kural","örnek","sistem","bilim","sanat","spor",
    "tarih","doğa","toplum","aile","çocuk","anne","baba","kardeş","arkadaş","komşu",
    "öğretmen","doktor","mühendis","yazar","gazeteci","avukat","hemşire","polis",
    "asker","çiftçi","öğrenci","patron","işçi","müdür","başkan","kral","kraliçe",
    "kahraman","düşman","misafir","yolcu"
  ],
  es: [
    "el","la","de","que","y","a","en","un","ser","se","no","haber","por","con","su",
    "para","como","estar","tener","le","lo","todo","pero","más","hacer","o","poder",
    "decir","este","ir","otro","ese","si","me","ya","ver","porque","dar","cuando",
    "muy","sin","vez","mucho","saber","qué","sobre","mi","alguno","mismo","yo","también",
    "hasta","año","dos","querer","entre","así","primero","desde","grande","eso","ni",
    "nos","llegar","pasar","tiempo","ella","sí","día","uno","bien","poco","deber",
    "entonces","poner","cosa","tanto","hombre","parecer","nuestro","tan","donde","ahora",
    "parte","después","vida","quedar","siempre","creer","hablar","llevar","dejar",
    "nada","cada","seguir","menos","posible","verdad","aquí","forma","contra","partir",
    "orden","muerte","noche","nunca","agua","aire","lugar","ayuda","voz","mundo",
    "tierra","madre","padre","hijo","hermano","casa","calle","puerta","mesa","silla",
    "libro","fuego","mar","cielo","sol","luna","estrella","flor","árbol","animal",
    "perro","gato","pájaro","pez","rojo","azul","verde","amarillo","negro","blanco",
    "grande","pequeño","alto","bajo","bueno","malo","bonito","feo","caliente","frío",
    "rápido","lento","duro","blando","feliz","triste","cansado","enfermo","contento",
    "enfadado","amor","odio","paz","guerra","sueño","realidad","cierto","falso","libre",
    "fácil","difícil","joven","mayor","mejor","peor","lejos","cerca","dentro","fuera",
    "arriba","abajo","delante","detrás","antes","después","ayer","hoy","mañana",
    "siempre","nunca","pronto","tarde","temprano","ahora","entonces","mientras",
    "durante","hasta","desde","entre","según","contra","hacia","para","por","sin",
    "sobre","tras","mediante","excepto","incluso","además","tampoco","también"
  ],
  az: [
    "və","bu","ilə","üçün","mən","sən","biz","onlar","var","çox","daha","kimi","olar",
    "ki","de","nə","amma","ya","hər","heç","necə","niyə","zaman","yaxşı","pis","böyük",
    "kiçik","yeni","köhnə","gün","il","insan","dünya","həyat","çətin","asan","sürətli",
    "yavaş","gözəl","doğru","yanlış","ilk","son","başqa","vacib","bilgi","sevgi","yol",
    "ev","şəhər","pul","iş","su","rəng","səs","göz","əl","baş","yer","gecə","səhər",
    "hava","işıq","qapı","masa","kitab","söz","düşüncə","gəlmək","getmək","görmək",
    "bilmək","istəmək","sevmək","olmaq","etmək","demək","tapmaq","almaq","vermək",
    "baxmaq","çalışmaq","düşünmək","danışmaq","anlamaq","oxumaq","yazmaq","öyrənmək",
    "gözləmək","görüşmək","dönmək","gətirmək","aparmaq","qaçmaq","oturmaq","qalxmaq",
    "girmək","çıxmaq","açmaq","bağlamaq","tutmaq","buraxmaq","başlamaq","bitmək",
    "seçmək","soruşmaq","cavab","saat","dəqiqə","həftə","ay","yüz","min","maşın",
    "təyyarə","gəmi","telefon","kompüter","internet","musiqi","film","məktəb",
    "xəstəxana","bazar","restoran","park","küçə","prospekt","bina","körpü","dəniz",
    "göl","çay","dağ","meşə","çiçək","ağac","daş","torpaq","od","qar","yağış",
    "günəş","səma","bulud","sabah","günorta","axşam","gecə","bu gün","sabah","dünən",
    "indi","sonra","əvvəl","həmişə","artıq","hələ","təkcə","hətta","bəlkə","bəli",
    "yox","tamam","salam","günaydın","isti","soyuq","təmiz","açıq","bağlı","dolu",
    "boş","ağır","yüngül","sərt","yumşaq","gerçək","yalan","vacib","məna","vəziyyət",
    "problem","həll","fikir","plan","nəticə","uğur","səhv","qayda","nümunə","sistem",
    "elm","sənət","idman","tarix","təbiət","cəmiyyət","ailə","uşaq","ana","ata",
    "qardaş","bacı","dost","qonşu","müəllim","həkim","mühəndis","yazar","jurnalist",
    "vəkil","polis","əsgər","tələbə","işçi","direktor","prezident","qəhrəman","qonaq"
  ]
};

const QUOTES = [
  // ── short (≤8 words) ──────────────────────────────────────────────────────
  "Be yourself everyone else is taken.",
  "Stay hungry stay foolish.",
  "Dream big work hard.",
  "Less talk more action.",
  "Do what you love.",
  "Make it simple but significant.",
  "Simplicity is the ultimate sophistication.",
  "Code is poetry written in logic.",
  "Think different act bold.",
  "Done is better than perfect.",
  // ── medium (9–15 words) ───────────────────────────────────────────────────
  "The only way to do great work is to love what you do.",
  "In the middle of every difficulty lies opportunity.",
  "Life is what happens when you are busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The only impossible journey is the one you never begin.",
  "Your time is limited so dont waste it living someone else life.",
  "In three words I can sum up everything about life it goes on.",
  "You miss one hundred percent of the shots you never take.",
  "Whether you think you can or think you cannot you are right.",
  "What you get by achieving your goals is not as important as who you become.",
  "The best time to plant a tree was twenty years ago the second best time is now.",
  // ── long (16–25 words) ────────────────────────────────────────────────────
  "Success is not final failure is not fatal it is the courage to continue that counts when everything feels impossible.",
  "The difference between ordinary and extraordinary is that little extra effort you put in every single day without exception.",
  "It always seems impossible until it is done and then you wonder why it took you so long to finally begin.",
  "If you want to live a happy life tie it to a goal not to people or things around you that change.",
  "Strive not to be a success but rather to be of value to those around you and to the world you live in.",
  "Twenty years from now you will be more disappointed by the things you did not do than by the ones you did so explore.",
  "The secret of getting ahead is getting started and breaking your complex overwhelming tasks into small manageable actionable steps every morning.",
  // ── thicc (>25 words) ─────────────────────────────────────────────────────
  "I have not failed I have just found ten thousand ways that will not work and each one brings me closer to the solution that will finally change everything around me.",
  "The greatest glory in living lies not in never falling but in rising every time you fall because resilience is the true foundation of all great achievement in this world.",
  "It does not matter how many times you get knocked down all that matters is how many times you get up and keep pushing forward with everything you have inside you.",
  "First they ignore you then they laugh at you then they fight you then you win and when you win you realize the struggle itself was the entire point all along.",
  "The brick walls are not there to keep us out they are there to give us a chance to show how badly we want something and how far we will go to get it.",
  "If you can dream it you can do it always remember that this whole thing was started with a dream and a mouse and the belief that imagination and hard work have absolutely no limits whatsoever.",
  "Believe you can and you are halfway there the other half is showing up every single day putting in the work staying consistent even when the results are slow and the path is unclear and long."
];
